Geo and trip apps initialization
Supernovaxxx/ovni-rest-api pull request #14
Opened 2023-07-16 14:04 UTC by joaorighetto

2023-07-22 22:09 UTC, artu-hnrq requested changes

2023-07-22 22:09 UTC, artu-hnrq commented on trip/serializers.py
> +        bulk_list = [Waypoint(trip=trip, order=i, **waypoint) for (i, waypoint) in enumerate(route, start=1)]
I would also advice against a choice like this `start=1`

It introduce almost no valuable impact over the solution, but yet it change the default expected behavior in a way that maintenance need to be accounted, it's a new business domain rule we need to treat.
This [magic number](https://stackoverflow.com/a/47890/2989289) won't stop appearing here at this function, it will be required to have this same logic propagated all over where we'll be dealing with this field... and besides, it even has a good reason for that.

Moreover

2023-07-24 14:53 UTC, artu-hnrq commented on trip/serializers.py
> +        return super(TripSerializer, self).update(instance, validated_data)
I'd suggest verify if the `update` method implementation on our Waypoint `ListSerializer` isn't enough

2023-07-24 14:56 UTC, artu-hnrq commented on trip/serializers.py
> +            bulk_update_list.append(old_waypoint)
Consider the approach of do all this case identification inside a single for loop

2023-07-24 14:57 UTC, artu-hnrq commented on trip/serializers.py
> +    order = serializers.IntegerField(read_only=True)
Is it really necessary?

2023-07-26 20:54 UTC, artu-hnrq requested changes
To be merged soon! :D

2023-07-26 20:54 UTC, artu-hnrq commented on trip/serializers.py
> +    order = serializers.IntegerField(write_only=True, required=False)
I was thinking about this field here. It seams it has not purpose at the end. 

We are using this `WaypointSerializer` only to validate the incomming data. And for the actual case, through the nested update from the `TripSerializer`, we are not expecting to receive the `order` field (but instead we'll get this from the array's order itself).

This way I'd suggest to remove it from here. We won't need it for now

2023-07-26 20:54 UTC, artu-hnrq commented on trip/serializers.py
> +def _generate_waypoints_list(trip, waypoints):
It's in the great intention of consistently provide a declaration distinction between:
- The trip's `route` (as `Waypoint` in-memory objects); And 
- A generic yet-to-be-transformed incoming _list of way points_ array data;
that I've repeatedly brought this subject up.

I see you using `waypoints` for both cases, but think it'd worth to transmit a bit more info through these variables names!

2023-07-26 22:34 UTC, joaorighetto commented on trip/serializers.py
> +    order = serializers.IntegerField(write_only=True, required=False)
If we remove this the `order` field will become visible in the response.

We didn't want this to happen, correct?

2023-07-27 14:40 UTC, artu-hnrq commented on trip/serializers.py
> +    order = serializers.IntegerField(write_only=True, required=False)
It'd be needed to include `order` on the `Meta.exclude` list then

2023-07-27 14:41 UTC, artu-hnrq commented on trip/serializers.py
> +    order = serializers.IntegerField(write_only=True, required=False)
It'd be needed to include `order` on the `Meta.exclude` list then

2023-07-27 15:11 UTC, merged