Joao feature event app
Supernovaxxx/ovni-rest-api pull request #2
Opened 2023-06-01 14:22 UTC by joaorighetto

2023-06-01 20:50 UTC, artu-hnrq requested changes
Ta massa a solução!
Deixei alguns comentários no código

2023-06-01 21:07 UTC, joaorighetto commented on __project__/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
Você ta falando da linha 8 ou linha 13?

2023-06-01 21:08 UTC, joaorighetto commented on event/models.py
> +    end_date = models.DateTimeField(auto_now=False, auto_now_add=False)
Certo, vou corrigir.

2023-06-02 00:47 UTC, artu-hnrq commented on __project__/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
Da 13, onde registrei o comentário!

2023-06-02 01:03 UTC, joaorighetto commented on __project__/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
Essa adição se deu por conta do tutorial do django rest framework. 
Lá de fato é dito que isso não é necessário mas simples e limpa de nos referirmos ao formato que queremos obter na response

2023-06-05 19:16 UTC, artu-hnrq approved these changes

2023-06-05 19:16 UTC, artu-hnrq approved these changes

2023-06-05 19:20 UTC, merged