Unit test implementation #2
Supernovaxxx/ovni-rest-api pull request #23
Opened 2023-08-30 04:35 UTC by joaorighetto

I'm creating this new pull request to include the changes from implementing the new custom admin command

2023-08-30 14:47 UTC, artu-hnrq requested changes
We are on the way!

2023-08-30 14:47 UTC, artu-hnrq commented on __project__/fixtures/sample.yaml
Why would us stop dealing with these fixtures?

2023-08-30 14:47 UTC, artu-hnrq commented on event/management/commands/generate_event_data.py
> +        parser.add_argument("-p", "--past", type=int, default=0)
Give a `help` description to each command's argument is very welcome!

2023-08-30 14:47 UTC, artu-hnrq commented on event/managers.py
>                  is_active=ExpressionWrapper(
I'd say we wouldn't need it anymore.

2023-08-30 14:47 UTC, artu-hnrq commented on event/tests/factories.py
> +Faker.add_provider(OptionalProvider)
Consider have these configuration on a centralized `compat` module

2023-08-30 14:47 UTC, artu-hnrq commented on event/tests/test_models.py
> +def test_event_active_manager_method(event_factory):
Change to deal with upcomming events

2023-08-30 14:47 UTC, artu-hnrq commented on event/tests/test_models_cases.py
> +def create_event_data_from_key_values(blank_key=None, null_key=None):
Consider use `factory_boy` as data generation engine

2023-08-30 22:15 UTC, joaorighetto commented on __project__/fixtures/sample.yaml
They were interfering with the tests

2023-08-31 14:59 UTC, artu-hnrq approved these changes
Baitão

2023-08-31 16:38 UTC, merged