build: starting containerization
Supernovaxxx/ovni-rest-api pull request #4
Opened 2023-06-09 22:55 UTC by pedr0prs

much to improve

2023-06-10 01:05 UTC, artu-hnrq requested changes
Ótimo começo, Pedrão!
Vamo que vamo

2023-06-10 01:05 UTC, artu-hnrq commented on Dockerfile
> +COPY . .
Esse é um bom começo! E eu pedi pra seres mínimo... Show de bola 

Mas discutimos juntos como ter um único `COPY` vai de encontro a otimização que o Docker faz (durante o processo de build) ao usar _cache_ pra cada _layer_ da _imagem_ gerada por esse `Dockarfile`.

Dá uma olhada [nessa resposta][1] do Stackoverflow e na documentação que ela linka, e vê se consegue implementar uma melhora nesse nosso aquivo!

  [1]: https://stackoverflow.com/a/41557161/2989289

2023-06-10 01:05 UTC, artu-hnrq commented on Dockerfile
> +COPY . .
Um arquivo `.dockerignore` também é ponto importante do processo de build. Bora adicionar um nesse PR também!!
Na própria documentação tem uma [sessão especifica][1] sobre isso

  [1]: https://docs.docker.com/engine/reference/builder/#dockerignore-file

2023-06-11 15:22 UTC, artu-hnrq requested changes

2023-06-11 15:22 UTC, artu-hnrq commented on .dockerignore
> +.md
Não existe nenhum arquivo que seja apenas `.md` no repositório.

> Arquivos como `.dockerignore` (e tanmbém o `.gitignore`) listam rexpressões regulares que serão aplicadas a cada arquivo do mesmo diretório afim de marcá-los como ignorados ou não.

Assim, me parece que talvez quisesses `*.md`, não?

2023-06-11 15:22 UTC, artu-hnrq commented on .dockerignore
> +.md
Além disso há outros arquivos que poderiam ser ignorados aqui
A pasta `.git` é um exemplo... nós não precisaremos versionar nada de dentro do container. Queremos apenas o atual estado da aplicação

2023-06-11 15:22 UTC, artu-hnrq commented on Dockerfile
> +EXPOSE 8000
Esse `Dockerfile` funciona? A aplicação rodou corretamente aqui?
Porque estas instalando as dependências em uma pasta e executando a aplicação de outra

2023-06-11 15:22 UTC, artu-hnrq commented on Dockerfile
> +EXPOSE 8000
E outra, porque o comando `CMD` foi excluido desse `Dockerfile`? 
Ele roda a aplicação sem esse commando?

2023-06-17 18:55 UTC, artu-hnrq requested changes
Agora tamos avançando de verdade!
Dei checkout desse branch na minha maquina e rodou liso...
Mais ainda tem alguns detalhes pra ajustar nesses aquivos, eu diria

Vamo que vamo!

2023-06-17 18:55 UTC, artu-hnrq commented on Dockerfile
> +# selected image. I think that in ubuntão it could be more agile, then I will carry out a test..
Usualmente, comentários nos arquivos se restringem a descrever o seu funcionamento, fortalecendo alguma legibilidade que não seja tão favorável pelo próprio código.

Comentários sobre o estágio de desenvolvimento de uma funcionalidade são melhor acomodados direto no _pull request_, que daí sim é o ambiente que se destina a promover comunicação entre a equipe, durante o processo de integração de código.

2023-06-17 18:55 UTC, artu-hnrq commented on Dockerfile
> +COPY . /app
Aqui vale a questão:
Se o `WORKDIR` é `/app` porque não referencia-lo com um `.` tal qual feito na linha 10, no `COPY` anterior?

Aponto até esses detalhes, pois é neles que concretizamos os entendimentos sutis

2023-06-17 18:55 UTC, artu-hnrq commented on Dockerfile
> +# selected image. I think that in ubuntão it could be more agile, then I will carry out a test..
Ainda assim é uma prática comum se encontrar `TODO`s direto nos arquivos, pontuando alguma limitação da implementação atual ou alguma solução temporária que precisa ser revista.

Diversas IDEs dão suporte a encontrar e listar ocorrência de `TODO` nos arquivos.
Ainda assim acredito que seja algo pra ser usado com bastante critério

2023-06-28 13:27 UTC, pedr0prs reviewed
vamos dar continuidade e explorar novas possibilidades nesse dockerfile

2023-06-28 23:22 UTC, pedr0prs commented
Vejo muito aprendizado e evolução neste PR.
Muito obrigado mestre por essa oportunidade.
Vamos pra cima

2023-06-28 23:22 UTC, closed without merging