build: Containerizing the application
Supernovaxxx/ovni-rest-api pull request #8
Opened 2023-06-29 14:08 UTC by pedr0prs

In this dockerfile, I used an official python image, defined the directory where the application will run, created a group and user and gave the necessary permission in /opt. I learned that it is good practice to use a virtual environment to isolate project dependencies. I installed the necessary requirements for the application without caching, prepared, started and ran the application pointing to port 8000.
Thank you for this progress...

2023-06-30 20:21 UTC, artu-hnrq requested changes
Ta mais robusto esse Dockerfile, heim? Tamos evoluindo!!

2023-06-30 20:21 UTC, artu-hnrq commented on Dockerfile
> +RUN python -m venv /opt/venv
O pacote python `venv` (virtual environment) tem como objetivo organizar específicas versões das dependências de um programa Python, especialmente no caso em que esse roda junto a outros pacotes que podem ter outras versões das mesmas dependências, proporcionando então isolamento.

O que acontece é que, quando conteinerizamos nossa aplicação, ela já está isolada. Não rodaremos nenhum outro programa dentro desse container. Ele está por inteiro destinado especificamente a conter o estado de execução mais atômico da nossa aplicação.

Portanto não há necessidade de usar do `venv` pra isolá-lo aqui.

2023-06-30 20:21 UTC, artu-hnrq commented on Dockerfile
> +RUN pip install --no-cache-dir -r requirements.txt
Além do mais, se olhares nosso `Makefile`, ele já traz a facilidade de isolar a aplicação (condicionalmente ao suprimento de uma _env var_), assim como já instala as dependências do projeto.
E seria [DRY][1] não replicar esse código, controlando as formas de fazê-lo de um único mesmo lugar.

  [1]: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

2023-06-30 20:21 UTC, artu-hnrq commented on Dockerfile
> +RUN make init
> O `Makefile` descreve o que eles chamam de _rules_, cada uma delas tem um _target_, assim como _prerequisitos_ e uma _receita_ Vale consultar a documentação oficial sobre [Rule Syntax][1] pra entender um pouquinho mais.

O grande ponto aqui é que quando um _target_ é chamado, todos os seus _prérequisitos_ são executados logo antes de sua própria execução.
O que faz com que, no nosso caso, `prepare` sempre rode antes de `init`, o que torna desnecessária a linha 15 desse `Dockerfile`. Compreende?

  [1]: https://www.gnu.org/software/make/manual/html_node/Rule-Syntax.html

2023-06-30 20:21 UTC, artu-hnrq commented on Dockerfile
> +RUN groupadd -r CPops && useradd -r -g CPops CPops && chown -R CPops:CPops /opt
Eu acrescentaria o questionamento sobre a escolha da nomeclatura desse grupo e usuário.
O que seria `CPops`?

2023-06-30 20:27 UTC, artu-hnrq commented
> ... without caching, prepared, started and ran the application pointing to port 8000...

Você não rodou a aplicação pra testar se o `Dockerfile` estava funcionando?

Assim vai ser difícil de tu perceber quando parou de funcionar.
Testar a cada modificação, uma a uma, é a maneira de tu poder progredir confiante de que estas num estado em que a aplicação ta rodando corretamente, podendo se aprofundar pra entender quando uma nova modificação introduzir um erro

2023-07-03 15:41 UTC, pedr0prs commented on Dockerfile
> +RUN groupadd -r CPops && useradd -r -g CPops CPops && chown -R CPops:CPops /opt
Sim, faz sentido, vou deixa-lo mais elegante e testar uma coisinha nova também....
CPops - Container Pedro Ops kakakakaka

2023-07-03 15:41 UTC, pedr0prs commented on Dockerfile
> +RUN python -m venv /opt/venv
entendido !

2023-07-04 12:09 UTC, pedr0prs commented on Dockerfile
> +RUN pip install --no-cache-dir -r requirements.txt
makefile é mt bom namoral, delicinha

2023-07-04 13:10 UTC, pedr0prs commented
Rodei a aplicação, está funcionando, porém, vou tentar fazer uma coisa nova aqui pra ver as possibilidade com Docker ;)

2023-07-05 13:09 UTC, closed without merging